export const ARTIST_SEARCH = 'ARTIST_SEARCH';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const GET_MORE = 'GET_MORE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const CLEAR_DETAILS = 'CLEAR_DETAILS';

export const GET_DIRECTIONS = 'GET_DIRECTIONS';
